# Header
menu:
  Home: .
  Archives: archives
  Research: research
  Links: links
  About: about


# Content
excerpt_link: Read More
fancybox: true

# Profile
profile: false # whether to show profile bar

# Sidebar
sidebar: false
widgets:
- recent_posts
- category
- tag: false
- tagcloud
- archive
thumbnail: true

# Contacts
contacts:
  github: http://github.com/quxiaofeng
  weibo: http://www.weibo.com/quxiaofeng
  twitter: http://twitter.com/quxiaofeng
  facebook: http://facebook.com/quxiaofeng
  # dribbble: http://dribbble.com/quxiaofeng
  zhihu: http://www.zhihu.com/people/quxiaofeng
  douban: http://www.douban.com/people/gBlueBird
  rss: atom.xml

# Links
links:
  Hexo: http://hexo.io

# Miscellaneous
google_analytics: UA-50831338-1
favicon: images/favicon.png
twitter: http://twitter.com/quxiaofeng
google_plus:
fb_admins:
fb_app_id:
